-- Purpose: explicit multi-floor connectors anchored exclusively to door access points.
-- Dependencies: immutable 2026-08-26 baseline, PostGIS and pgRouting.
-- Objects: routing_floors, routing_connectors, routing_connector_stops, routing functions.
-- Routing: per-floor edges remain unchanged; live transfer edges resolve regenerated nodes.
-- Rollback: deploy old application, then the matching down.sql; connector records are removed.
BEGIN;

CREATE TABLE public.routing_floors (
    floor smallint PRIMARY KEY,
    label text NOT NULL,
    sort_order integer NOT NULL UNIQUE
);
INSERT INTO public.routing_floors VALUES (-1, 'منفی ۱', -1), (0, 'همکف', 0);
INSERT INTO public.routing_floors
SELECT DISTINCT floor, 'طبقه ' || floor, floor FROM public.areas
ON CONFLICT DO NOTHING;

-- Floors are identifiers; no elevation-within-a-floor model is introduced.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['areas','doors','door_access_points','mesh_triangles',
    'poi_points','route_logs','admin_restrictions','van_nodes'] LOOP
    EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT IF EXISTS %I', t, t || '_floor_check');
    EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I FOREIGN KEY (floor) REFERENCES public.routing_floors(floor)', t, t || '_routing_floor_fk');
  END LOOP;
END $$;

CREATE TABLE public.routing_connectors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind text NOT NULL CHECK (kind IN ('stair','ramp','elevator','escalator')),
    info jsonb NOT NULL DEFAULT '{}'::jsonb,
    is_active boolean NOT NULL DEFAULT false,
    direction text NOT NULL DEFAULT 'both' CHECK (direction IN ('both','forward','reverse')),
    wait_seconds numeric NOT NULL DEFAULT 0 CHECK (wait_seconds >= 0 AND wait_seconds <= 3600),
    version integer NOT NULL DEFAULT 1,
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.routing_connector_stops (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_id bigint NOT NULL REFERENCES public.routing_connectors(id) ON DELETE CASCADE,
    door_id bigint NOT NULL UNIQUE REFERENCES public.doors(id) ON DELETE CASCADE,
    access_id bigint REFERENCES public.door_access_points(id) ON DELETE SET NULL,
    area_id bigint NOT NULL REFERENCES public.areas(id),
    floor smallint NOT NULL REFERENCES public.routing_floors(floor),
    position integer NOT NULL CHECK (position >= 0),
    travel_seconds numeric NOT NULL CHECK (travel_seconds > 0 AND travel_seconds <= 3600),
    reverse_seconds numeric CHECK (reverse_seconds > 0 AND reverse_seconds <= 3600),
    UNIQUE (connector_id, floor),
    UNIQUE (connector_id, position)
);
CREATE INDEX routing_connector_stops_connector_idx ON public.routing_connector_stops(connector_id);

-- Resolve DAPs by explicit identity; after a rebuild only an unambiguous replacement
-- belonging to the same door AND area may be used. Never persist routing_node IDs.
CREATE VIEW public.routing_connector_nodes AS
SELECT s.*, rn.id AS node_id, rn.geom, c.kind, c.is_active, c.direction, c.wait_seconds
FROM public.routing_connector_stops s
JOIN public.routing_connectors c ON c.id=s.connector_id
CROSS JOIN LATERAL (
  SELECT min(dap.id) AS id
  FROM public.door_access_points dap
  WHERE dap.door_id=s.door_id AND dap.floor=s.floor AND NOT dap.needs_review
    AND s.area_id IN (dap.from_area, dap.to_area)
    AND (s.access_id IS NULL OR dap.id=s.access_id)
  HAVING count(*)=1
) d
JOIN public.routing_nodes rn ON rn.ref_table='door_access_points'
  AND rn.ref_id=d.id AND rn.floor=s.floor AND rn.area_id=s.area_id
JOIN public.areas a ON a.id=s.area_id AND a.floor=s.floor;

-- A removed stop invalidates the connector until an administrator reviews it.
CREATE FUNCTION public.fn_connector_stop_removed() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.routing_connectors SET is_active=false, version=version+1, updated_at=now()
  WHERE id=OLD.connector_id;
  RETURN OLD;
END $$;
CREATE TRIGGER connector_stop_removed AFTER DELETE ON public.routing_connector_stops
FOR EACH ROW EXECUTE FUNCTION public.fn_connector_stop_removed();

CREATE OR REPLACE FUNCTION public.fn_allowed_areas(p_now timestamp with time zone, p_gender public.gender_enum, p_mode text, p_floor smallint) RETURNS TABLE(id bigint, geom public.geometry, area_type public.area_type_enum, floor smallint, allowed_gender public.gender_enum, is_closed boolean, weight_open_space numeric, attrs jsonb, is_allowed boolean, admin_penalty_w numeric)
    LANGUAGE sql STABLE
    AS $$

WITH blocked_raw AS (

    SELECT
        ba.area_id,
        ba.restrict_type,
        ba.penalty_w

    FROM public.fn_blocked_areas_from_admin(
        p_now,
        p_gender,
        p_mode,
        p_floor
    ) ba
),

blocked AS (

    SELECT
        area_id,

        CASE
            WHEN bool_or(restrict_type = 'close')
                THEN 'close'

            ELSE MIN(restrict_type)
        END AS restrict_type,

        MAX(
            COALESCE(penalty_w, 0.0)
        ) AS penalty_w

    FROM blocked_raw

    GROUP BY area_id
)

SELECT
    a.id,
    a.geom,
    a.area_type,
    a.floor,
    a.allowed_gender,
    a.is_closed,
    a.weight_open_space,
    a.attrs,

    CASE

        --------------------------------------------------------------
        -- area اصولاً routable نیست
        --------------------------------------------------------------
        WHEN public.fn_area_routing_role(
                 a.area_type,
                 a.attrs
             ) <> 'routable'
            THEN FALSE


        --------------------------------------------------------------
        -- ویلچر از پله عبور نکند
        --------------------------------------------------------------
        WHEN p_mode = 'wheelchair'
             AND a.area_type::text = 'stair_area'
            THEN FALSE


        --------------------------------------------------------------
        -- محدوده بدون DAP قابل استفاده در گراف نیست
        --------------------------------------------------------------
        WHEN COALESCE(ds.door_cnt, 0) = 0
             AND NOT EXISTS (SELECT 1 FROM public.routing_connector_stops cs WHERE cs.area_id=a.id AND cs.floor=a.floor)
            THEN FALSE


        --------------------------------------------------------------
        -- محدودیت زمان / نماز / admin از fn_entity_access
        --------------------------------------------------------------
        WHEN COALESCE(acc.allowed, TRUE) = FALSE
            THEN FALSE


        --------------------------------------------------------------
        -- بسته بودن دائمی area
        --------------------------------------------------------------
        WHEN a.is_closed = TRUE
            THEN FALSE


        --------------------------------------------------------------
        -- Admin close
        --------------------------------------------------------------
        WHEN b.restrict_type = 'close'
            THEN FALSE


        ELSE TRUE

    END AS is_allowed,

    COALESCE(
        b.penalty_w,
        0.0
    ) AS admin_penalty_w

FROM public.areas a

LEFT JOIN blocked b
       ON b.area_id = a.id

LEFT JOIN public.mv_area_door_stats ds
       ON ds.area_id = a.id

LEFT JOIN LATERAL (

    SELECT
        ea.allowed

    FROM public.fn_entity_access(
        'areas',
        a.id,
        p_now,
        p_gender,
        p_mode,
        p_floor,

        -- area.geom مجاز است
        ST_PointOnSurface(a.geom)
    ) ea

    LIMIT 1

) acc ON TRUE

WHERE
    a.floor = p_floor

    AND (

        --------------------------------------------------------------
        -- family
        --------------------------------------------------------------
        (
            p_gender = 'both'::gender_enum
            AND a.allowed_gender = 'both'::gender_enum
        )

        OR

        --------------------------------------------------------------
        -- male / female
        --------------------------------------------------------------
        (
            p_gender IN (
                'male'::gender_enum,
                'female'::gender_enum
            )

            AND (
                a.allowed_gender = 'both'::gender_enum
                OR a.allowed_gender = p_gender
            )
        )
    );

$$;

COMMIT;
