# --- Memory ---
shared_buffers = 2GB            # حدود 25% رم
effective_cache_size = 6GB     # حدود 60–70% رم
work_mem = 64MB                 # برای هر sort/join؛ اگر کانکشن زیاد داری، پایین‌تر بگیر (مثلاً 32MB)
maintenance_work_mem = 1GB

# --- WAL & Checkpoint ---
wal_compression = on
checkpoint_timeout = 15min
max_wal_size = 6GB
min_wal_size = 1GB

# --- Parallelism ---
max_worker_processes = 8
max_parallel_workers_per_gather = 4
max_parallel_workers = 8

# --- Planner ---
random_page_cost = 1.1
effective_io_concurrency = 200

# --- Logging (برای بررسی کندی) ---
log_min_duration_statement = 500      # هر کوئری بالای 500ms را لاگ کن
log_checkpoints = on
log_autovacuum_min_duration = 0

# --- Locale / Etc (اگر در init ست شده است، لازم نیست دست بزنی) ---
# lc_messages = 'C'
# lc_monetary = 'C'
# lc_numeric = 'C'
# lc_time = 'C'

listen_addresses = '*'
port = 5432
